name: json_data_explorer
description: A highly customizable widget to render and interact with JSON objects.
version: 0.1.2
repository: https://github.com/foss42/json_data_explorer
homepage: https://github.com/foss42/json_data_explorer
issue_tracker: https://github.com/foss42/json_data_explorer/issues

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: 0.1.1
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
