name: data_explorer_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.7.2"

dependencies:
  flutter:
    sdk: flutter
  json_data_explorer:
    path: ../

  http: ^1.1.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  rows_lint: 0.1.0

flutter:
  uses-material-design: true
